# Generated by Django 3.1.4 on 2020-12-01 17:36

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="nr_like",
            field=models.IntegerField(default=0),
        ),
    ]
